services:
  mysql:
    image: mysql:8.0
    container_name: eventhub_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: eventhub
      MYSQL_USER: eventhub_user
      MYSQL_PASSWORD: eventhub123
    ports:
      - "3306:3306"
    volumes:
      - eventhub_data:/var/lib/mysql
      - ./banco/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eventhub_net

  backend:
    build: ./backend
    container_name: eventhub_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: eventhub_user
      DB_PASSWORD: eventhub123
      DB_NAME: eventhub
      PORT: 3000
      JWT_SECRET: troque_por_uma_chave_secreta_forte
      JWT_EXPIRES_IN: 7d
    depends_on:
      - mysql
    networks:
      - eventhub_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: eventhub_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: eventhub_user
      PMA_PASSWORD: eventhub123
    depends_on:
      - mysql
    networks:
      - eventhub_net

  frontend:
    image: nginx:alpine
    container_name: eventhub_frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - eventhub_net

volumes:
  eventhub_data:

networks:
  eventhub_net:
    driver: bridge